### ISSUE TITLE
クラス名の表記：完全修飾からミニマム修飾に変える

### ISSUE THREAD

**Issue by masuda220** [irof/Jig#45]
classリストのクラス名の完全修飾名が冗長

*.service
*.domain.[model|basic]

までの修飾は、非表示にしたい。
service, domain.model も非表示

その他のアイデア

完全修飾名は、オプションで表示する（デフォルトは、表示しない）
完全修飾名と最少修飾名を２つのカラムに出力し、使う側がカラムの非表示などの対応をする

**Comment by irof** [comment]
78c4f9ee44d4dcaf18415677da6ec903f5a2ae9e で非表示にしました。
正規表現で指定、デフォルトは次にしています。

```
output.omit.prefix=.+\\.(service|domain\\.(model|basic))\\.
```

切り替え #52 や持ち方 #50 は別検討。
