### ISSUE TITLE
質問：パッケージ図に表示されるロジック（表示されないケース）

### ISSUE THREAD

**Issue by masuda220** [irof/Jig#46]
model 以下のパッケージで、表示されるものと表示されないものがある。
表示されないのは、どういう条件の時か？

**Comment by irof** [comment]
importがなくても関連があれば表示されます。

`*.java` ではなく `*.class` を解析しているため、例えば以下の `Fuga` クラスの `toBaz` メソッドのようにメソッドチェーンで使用しているものであっても、 `Baz` クラスへの関連は取得されます。

https://github.com/irof/Jig/blob/5dae6d7950225daf378e545581ac41050b462328/jig-core/src/test/java/stub/domain/model/relation/fuga/Fuga.java#L24-L27

パッケージ図に表示されない条件として考えられるのは、 `domain.model` パッケージ以下に関連が存在しない場合になります。（たとえばserviceパッケージのクラスからしか使用されておらず、他の `domain.model` パッケージのクラスを参照していないものなど。）

**Comment by masuda220** [comment]
以下は？

パッケージ名だけ　（クラスも、サブパッケージもない）
パッケージ直下にクラス一つ（クラスは名前の宣言だけで、何もない）

**Comment by irof** [comment]
パッケージだけのものは出力されません。

パッケージ直下にクラス1つだけのものは、そのクラスが他パッケージから参照されていれば表示されます。

**Comment by masuda220** [comment]
内容理解しました。
質問としてはクローズ。
