### ISSUE TITLE
要望：依存関係のないパッケージも、孤立パッケージとして表示したい

### ISSUE THREAD

**Issue by masuda220** [irof/Jig#47]
model 以下のパッケージは、依存関係がない場合も、孤立したパッケージとして、存在だけは、パッケージ図に表示したい

**Comment by irof** [comment]
link #20

**Comment by irof** [comment]
0c0f275fce5f1bcbe60ef0b81f1d286af0a8f23e
MODELと判別されるクラスが所属するパッケージを表示するようにしました。

MODELの条件は「識別子に `.domain.model.` が含まれるもの」です。
https://github.com/irof/Jig/blob/5dae6d7950225daf378e545581ac41050b462328/jig-core/src/main/java/jig/domain/model/characteristic/Characteristic.java#L84-L89
https://github.com/irof/Jig/blob/5dae6d7950225daf378e545581ac41050b462328/jig-core/src/main/java/jig/domain/model/specification/Specification.java#L73-L76
