### ISSUE TITLE
新機能：バリデーションアノテーションの一覧

### ISSUE THREAD

**Issue by masuda220** [irof/Jig#57]
class-list 系の新機能

バリデーションを記述したクラスと、バリデーション記述の一覧

（親子クラスの構造表示は別issueにわける）

**Comment by masuda220** [comment]
本日追加したissueの中で、もっとも優先度が高い。とりあえず版がほしい。

**Comment by irof** [comment]
一覧にシートを追加して出力するようにしました。

https://github.com/system-sekkei/isolating-the-domain で実行すると次のようにでます。

![2018-04-21 11 48 24](https://user-images.githubusercontent.com/615346/39079642-1a14e116-455a-11e8-8208-209eb3a9cdb8.png)

**Comment by irof** [comment]
とりあえず版ということで

- 対象のアノテーションがBeanValidationとHibernateValidatorのみとなっています。（パッケージで識別しています）
- アノテーションパラメータが配列やアノテーションの場合は完全な情報が出力できません。（ネストが複雑になるため実装に時間がかかる見込み）

参考: [READMEの補足](https://github.com/irof/Jig/tree/master/class-list-cli#%E8%A3%9C%E8%B6%B3-%E3%83%90%E3%83%AA%E3%83%87%E3%83%BC%E3%82%B7%E3%83%A7%E3%83%B3%E6%83%85%E5%A0%B1)

**Comment by masuda220** [comment]
ありがとうございます。
とりあえず版としては、十分です。
