### ISSUE TITLE
拡張：イベントハンドラメソッドであることの表示

### ISSUE THREAD

**Issue by masuda220** [irof/Jig#59]
サービスクラスのメソッド一覧で、イベントハンドラ（コントローラから直接呼ばれるメソッド）であることを表示する

**Comment by masuda220** [comment]
比較的、はやめにほしい

**Comment by irof** [comment]
一覧のSERVICEシートにイベントハンドラ列を追加しました。

https://github.com/system-sekkei/isolating-the-domain で実行すると次のようにでます。（いずれもControllerから呼ばれているため、全部◯になっています。）

![2018-04-22 19 41 57](https://user-images.githubusercontent.com/615346/39094184-9a64ac72-4666-11e8-8d04-40a1cda77fb2.png)

呼び出し元メソッドのクラスに `org.springframework.stereotype.Controller` か `org.springframework.web.bind.annotation.RestController` が付いている場合、イベントハンドラと判定します。
