### ISSUE TITLE
新機能：文字列比較の列挙

### ISSUE THREAD

**Issue by masuda220** [irof/Jig#66]
ビジネスルールの分類判定などに使っていると思われる、文字列比較箇所の列挙

**Comment by irof** [comment]
`String#equals` メソッドの呼び出しを抽出する。

Stringの文字列比較は `xxxId.value().equals(yyyId.value())` のような感じで使用されることがあり、本来ドメインに表現するべきビジネスルールが埋もれている可能性があるため。

**Comment by irof** [comment]
一覧に「文字列比較箇所」シートを追加し、`String#equals(Object)` を呼び出しているメソッドを列挙するようにしました。
出力項目はクラス名とメソッド名だけです。
